[env]
MISE_EXPERIMENTAL = 1

[tools]
go = "latest"
java = "zulu-25"
maven = "3.9.16"
"npm:@mermaid-js/mermaid-cli" = "latest"
node = "lts"
uv = "latest"

[settings]
idiomatic_version_file_enable_tools = ["node", "python", "java", "go"]
